name: Build and Upload Artifact

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Build Commands
        run: |
          echo "🔧 Starting build process..."
          mkdir -p output
          echo "Build successful!" > output/build-log.txt

      - name: Run Tests
        run: |
          echo "🧪 Running tests..."
          mkdir -p output
          echo "All tests passed!" > output/test-results.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: output/
